name: project_handling_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  google_fonts: ^6.2.1
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^27.1.57
  smooth_page_indicator: ^1.2.0+3
  page_transition: ^2.1.0
  lottie: ^3.1.3  # Updated
  swipeable_button_view: ^0.0.2
  table_calendar: ^3.0.0
  image_picker: ^1.1.2 # Updated
  horizontal_calendar: ^1.1.2 
  swipe_to: ^1.0.6
  provider: ^6.1.2
  vpn_connection_detector: ^1.0.9
  sqflite: ^2.3.3+1

flutter_native_splash:
  color: "#ffffff"  # Background color
  image: assets/splash.jpg  # Path to your splash image
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.jpg
    - assets/logo.jpg